# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 12:50
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('Наименование', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('Код', models.CharField(max_length=3, unique=True)),
                ('За_единица', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(99999)])),
                ('Лева', models.DecimalField(decimal_places=5, max_digits=10)),
            ],
            options={
                'ordering': ('Наименование',),
            },
        ),
    ]
